### ISSUE TITLE
FatalThrowableError in Transformer.php line 230

### ISSUE THREAD

**Issue by spacecomx** [logaretm/transformers#1]
The transformer using with() only works if there is at least one photo record for each product. If not the transformer fails.

```
   $transformer = Transformer::make(Product::class);

   $products = \App\Product::with('photos')->get();

  $transformer->with('photos')->transform($products);
```

The Product model relationship with the Photo model

```
    public function photos()
    {
        return $this->hasMany(Photo::class);
    }
```

Should a product in the products collection not have an attached image record for that specific product the following error is thrown: 

> FatalThrowableError in Transformer.php line 230:
> Call to a member function transform() on null

The $transformer->with('photos')->transform($products) should allow for the products relationship with photos or tags etc, to have and empty array collection; for those products without photo records, and still return the product, photos collection.

**Comment by spacecomx** [comment]
The temp fix I used is was to add this code to Transformer.php under line 206. 

```
        // if the result is a collection and has no object pass empty array.
        if($result instanceof Collection && $result->isEmpty()) {
            return [];
        }

        // if the result has no object pass empty array.
        if($result == null) {
            return [];
        }
```

This will pass and empty array for both a collection and hasOne when not relationship is found.

**Comment by logaretm** [comment]
Thanks for providing a fix, I will add it shortly.

**Comment by spacecomx** [comment]
Hi,

Great product, thank you.

Just one thing, the code must be changed to from an array [] to null for hasOne relationships.

// if the result has no object pass empty array.
if($result == null) {
    return null;
}
Kind regards;

Wayne Gibson, Director
SpaceComX, Creative Design | Marketing | Web Agency | Mobile: +27 (72) 685 8551
PO Box 3786, Dainfern, Johannesburg, 2055, South Africa
Division of SpaceCom Alliance (Pty) Ltd

**Comment by logaretm** [comment]
Yes, I just pushed some code. I think if the relation doesn't return an object (like null) it should just return that relation. which would allow getters to be included in the transform as well.

**Comment by spacecomx** [comment]
Yes, I agree … thanks for the fix :)

Wayne Gibson, Director
SpaceComX, Creative Design | Marketing | Web Agency | Mobile: +27 (72) 685 8551
PO Box 3786, Dainfern, Johannesburg, 2055, South Africa
Division of SpaceCom Alliance (Pty) Ltd
