### ISSUE TITLE
tags option does not exists

### ISSUE THREAD

**Issue by nezaboravi** [logaretm/transformers#2]
Read thru your code and liked it :)
but getting error on php artisan vendor:publish --provider="Logaretm\Transformers\Providers\TransformerServiceProvider" --tags="config"

 [Symfony\Component\Console\Exception\RuntimeException]
  The "--tags" option does not exist.

running Laravel 5.4

**Comment by logaretm** [comment]
Hey @nezaboravi 

Glad you liked it. You can try to use `--tag` instead I'm not sure if it was a typo or it used to be that way.

**Comment by nezaboravi** [comment]
Thanks! It works great so far, i published it without any flag and got it working in no time. Thanks for great package, well documented and tested. Great job!
